#!/usr/bin/env bash
# Update Nginx configuration to listen on port 80

# Change port from 8080 to 80
sudo sed -i "s/listen 8080;/listen 80;/" /etc/nginx/sites-enabled/default

# Test Nginx configuration
sudo nginx -t

# Restart Nginx to apply the changes
sudo service nginx restart

# Stop Nginx to ensure it is not running
sudo service nginx stop
