#!/usr/bin/env bash
# Installs nginx server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chown www-data:www-data /var/www/html
sudo chmod 755 /var/www/html
sudo echo "Holberton School for the win!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
